In [1]:
library(IRdisplay)
display_html("<style>.container { width:100% !important; }</style>")

.libPaths()

[1] "/nfs/research/marioni/Leah/software/conda_envs/deconvolution/lib/R/library"

In [2]:
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(viridis))
#suppressPackageStartupMessages(library(DirichletReg))
suppressPackageStartupMessages(library(matrixStats))
suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(edgeR))
suppressPackageStartupMessages(library(tibble))
suppressPackageStartupMessages(library(abind))

In [3]:
opts <- list()
opts$g_meta <- '/nfs/research/marioni/Leah/gastrulation_epigenetics/gastruloid_characterisation/data_dir/processed_files_Leah/scRNAseq/sample_metadata_final2.txt.gz'
opts$functions <- '/nfs/research/marioni/Leah/gastrulation_epigenetics/gastruloid_characterisation/gastruloids_scRNAseq/pipeline_final/perturbation_simulations/DA_simulations_functions.R'
opts$timepoint <- 'd4.5'
source(opts$functions)

In [5]:
g_meta <- fread(opts$g_meta)

In [6]:
pca <- do_pca(df_ref=g_meta, tp=opts$timepoint, io=io)
saveRDS(pca, '/nfs/research/marioni/Leah/gastrulation_epigenetics/gastruloid_characterisation/data_dir/processed_files_Leah/scRNAseq/heterogeneity_simulations/d4.5_pca.RDS')


In [7]:
pca

$X
, , 1

            [,1]       [,2]       [,3]        [,4]        [,5]        [,6]
[1,]  0.04634491  0.2395400 0.29539156  0.04372063  0.34231802  0.18992978
[2,] -0.01278450 -0.5029234 0.05832824 -0.01722383 -0.10763491  0.17703440
[3,] -0.02256900 -0.3494674 0.31854838  0.30167019  0.09625863 -0.06309896
           [,7]       [,8]        [,9]       [,10]       [,11]      [,12]
[1,]  0.0841747 0.36834915 -0.27839569 -0.24068759  0.05311973 -0.1551113
[2,] -0.0169990 0.01442069  0.22800985  0.01313986 -0.05791831 -0.5405157
[3,]  0.2796768 0.14550894  0.01387487  0.01781536 -0.02681874  0.2998733
           [,13]      [,14]       [,15]       [,16]       [,17]       [,18]
[1,] -0.19874977  0.3649962 -0.08933052 -0.02396515 -0.15116945  0.04089773
[2,] -0.16165809 -0.2131792 -0.08533295  0.10949636  0.03011863 -0.12926221
[3,] -0.08867097 -0.1791748  0.27641058 -0.09596850  0.13615490  0.08610450
          [,19]       [,20]        [,21]      [,22]        [,23]       [,24]
[1,] -0.3476464 -0.10518525 -0.016292876 0.08410492  0.009515613  0.20107695
[2,] -0.3868490  0.16505738 -0.008027914 0.03117079 -0.015120914 -0.00690095
[3,]  0.1470202 -0.05091616  0.088440403 0.52147160 -0.072060986  0.08319350
           [,25]
[1,] -0.08591519
[2,] -0.25580339
[3,] -0.11613011

, , 2

              [,1]        [,2]       [,3]        [,4]        [,5] [,6]
[1,]  0.0003080639  0.02353859  0.3768200  0.49042582  0.04024084    0
[2,] -0.0226919688 -0.04237733 -0.3126247 -0.09370833 -0.22274587    0
[3,]  0.0000000000  0.00000000  0.0000000  0.00000000  0.00000000    0
           [,7]       [,8]        [,9]        [,10]       [,11]        [,12]
[1,]  0.2489053  0.2526831  0.02333192 -0.031587846  0.02605953 -0.032278335
[2,] -0.1568711 -0.3359703 -0.10943761 -0.003898415 -0.03820870  0.003603064
[3,]  0.0000000  0.0000000  0.00000000  0.000000000  0.00000000  0.000000000
          [,13]        [,14]     [,15]      [,16]       [,17]        [,18]
[1,] -0.2990273  0.007569114 0.1137405 -0.1734840 -0.22356037 -0.009780117
[2,] -0.2871391 -0.036176821 0.3975036 -0.4178903 -0.02276438  0.007637362
[3,]  0.0000000  0.000000000 0.0000000  0.0000000  0.00000000  0.000000000
           [,19]      [,20]       [,21]       [,22]       [,23]       [,24]
[1,] -0.43836183 -0.1533248 -0.05804676  0.04575049 -0.01560243  0.19532007
[2,] -0.03177271 -0.4295399  0.15224983 -0.07527271  0.08593281 -0.08878248
[3,]  0.00000000  0.0000000  0.00000000  0.00000000  0.00000000  0.00000000
          [,25]
[1,] -0.2100984
[2,] -0.2097771
[3,]  0.0000000


$ct_ordering
 [1] "Anterior Primitive Streak" "Cardiopharyngeal Mesoderm"
 [3] "Caudal Epiblast"           "Caudal Neurectoderm"      
 [5] "Early Anterior PSM"        "Early Nascent Mesoderm"   
 [7] "Early Neurectoderm"        "Early Posterior PSM"      
 [9] "Early Spinal Cord"         "Endothelium"              
[11] "Epiblast"                  "Head Mesoderm"            
[13] "Late Anterior PSM"         "Late Nascent Mesoderm"    
[15] "Late Neurectoderm"         "Late Posterior PSM"       
[17] "Late Spinal Cord"          "Mature Endoderm"          
[19] "Mature Somites"            "NMPs"                     
[21] "Neurons"                   "Notochord"                
[23] "PGCs"                      "Primitive Streak"         
[25] "Somites"                  

$offset
           [,1]      [,2]
 [1,] -6.999416 -6.852435
 [2,] -4.999510 -6.789319
 [3,] -4.592005 -4.789838
 [4,] -6.400975 -4.509235
 [5,] -3.996297 -5.848458
 [6,] -6.530566 -6.894670
 [7,] -6.519582 -5.928123
 [8,] -3.894032 -5.529418
 [9,] -3.622186 -1.375188
[10,] -5.801178 -6.740722
[11,] -6.753762 -6.428707
[12,] -4.275718 -6.779590
[13,] -3.508280 -4.986159
[14,] -4.867495 -6.779215
[15,] -6.038714 -3.531555
[16,] -2.184029 -4.203300
[17,] -6.210168 -1.435137
[18,] -3.003081 -6.308964
[19,] -2.356971 -3.927870
[20,] -3.007300 -3.684509
[21,] -7.067915 -6.360121
[22,] -4.572313 -5.558469
[23,] -6.904044 -6.787318
[24,] -5.837957 -6.276684
[25,] -